Model can be deleted only before certification of model versions
zigbee-alliance/distributed-compliance-ledger pull request #455
Opened 2023-03-22 11:44 UTC by lazizcodesatdsr

Point 3 in https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/421:
> Model can be deleted by the owner Vendor (account with the VID created the model) only before at least one of its Model Versions is certified and certification is issued by CSA.

2023-03-22 19:16 UTC, DenisRybas requested changes
Please add tests and pull changes from previous PR here (after processing comments)

2023-03-23 05:17 UTC, lazizcodesatdsr commented on x/model/handler_test.go
> +func TestHandler_DeleteModelWithAssociatedModelVersionsNotCertified(t *testing.T) {
@DenisRybas Ok, let's merge the previous PR (if everything is ok now), then I will sync this branch up and update the tests

2023-03-23 22:04 UTC, DenisRybas requested changes

2023-03-23 22:04 UTC, DenisRybas commented on x/model/handler_test.go
> +func TestHandler_DeleteModelWithAssociatedModelVersionsCertified(t *testing.T) {
@lazizcodesatdsr also please add integration tests for this case

2023-03-27 11:13 UTC, merged