#502 Add SchemaVersion field into PKI, Compliance, Model and VendorInfo schemas
zigbee-alliance/distributed-compliance-ledger pull request #552
Opened 2024-03-19 15:08 UTC by Abdulbois

2024-03-21 11:26 UTC, ashcherbakov commented on docs/transactions.md
>    - vendorLandingPageURL: `optional(string)` -  URL of the vendor's landing page
Please make sure that we have schemaVersion in docs for the following commands:
- ADD_PKI_REVOCATION_DISTRIBUTION_POINT
- UPDATE_PKI_REVOCATION_DISTRIBUTION_POINT
- Approve/Reject/Revoke wrappers for PKI commands (see https://github.com/zigbee-alliance/distributed-compliance-ledger/pull/552#discussion_r1533681328)

2024-03-21 11:27 UTC, ashcherbakov requested changes
- I think we need to have schemaVersion for auxiliary models as well: Accounts, Validator, Update.
- Please don't forget to update the PR description

2024-03-21 12:41 UTC, akarabashov commented
> * I think we need to have schemaVersion for auxiliary models as well: Accounts, Validator, Update.

Created task: https://github.com/zigbee-alliance/distributed-compliance-ledger/issues/556

2024-03-21 12:51 UTC, Abdulbois commented on proto/compliance/compliance_info.proto
> +  uint32 schemaVersion = 24;
Concern to make it `uint32`was that several existing Version fields in our schemas are `uint32`
Can we leave it as `uint32` or making it `uint16` strictly required?

2024-03-21 12:54 UTC, Abdulbois commented
> As the new field is optional, and we have to manually pass it to the object constructor in every handler and every CLI command, there is a risk that we may unintentionally forget to pass it somewhere. So, I would recommend to add such tests for **every** command. Either have a dedicated/separate test where we explicitly set schema version for all add/update commands and check that it has been set/updated, or extend existing Add/Update tests. I know that we already have such tests for some transactions, I think it's important to have it for all of them.
> 
> **Note**: it seems such checks (that we pass and apply optional parameters correctly) may be duplicated in unit and CLI tests. Although usually we prefer unit tests, in this case we may consider having CLI tests only (as it implicitly covers the unit test cases as well).

I think, currently all txn CLI calls are checked for using `schemaVersion` in their commands
To be sure wiil double check

2024-03-21 12:56 UTC, ashcherbakov commented on proto/compliance/compliance_info.proto
> +  uint32 schemaVersion = 24;
unit16 is defined by the Spec, our main document...
Please note though, that in the past we experienced some difficulties with uint16 on the .proto level, so it's defined as int32/unit32 in the main .proto, and restrictions are defined in `tx.proto`, see for example `vid` and `pid` fields.

2024-03-22 12:34 UTC, Abdulbois commented on proto/compliance/compliance_info.proto
> +  uint32 schemaVersion = 24;
Fixed with adding validation tag into `tx.proto` messages

2024-03-22 13:01 UTC, ashcherbakov approved these changes

2024-03-22 13:10 UTC, akarabashov commented on docs/transactions.md
> +  - schemaVersion: `optional(uint32)` - Schema version to support backward/forward compatability(default 0)
```suggestion
  - schemaVersion: `optional(uint16)` - Schema version to support backward/forward compatability(default 0)
```
Please correct it in other places as well

2024-03-22 13:38 UTC, akarabashov reviewed
I noticed that unit tests for static validation are missing, I think it makes sense to add them

2024-03-23 07:52 UTC, Abdulbois commented
> I noticed that unit tests for static validation are missing, I think it makes sense to add them

Added, please recheck

2024-03-25 10:21 UTC, akarabashov approved these changes

2024-03-25 10:22 UTC, merged